# =============================================================================
#  AI Job Application Agent - developer entry points.
#
#  WINDOWS WITHOUT make: there is nothing magic in here. Every target is one or
#  two ordinary commands, and they are written out in full below, so you can
#  copy the line for the target you want and paste it into your shell. Run them
#  from the repository root. `make -n <target>` prints the exact commands a
#  target would run without running them, which is the easiest way to read one.
#  These recipes are POSIX shell (git-bash, WSL, macOS, Linux); in cmd.exe you
#  will need to swap the forward slashes for backslashes.
# =============================================================================

# Locate the backend interpreter. PY is relative to backend/ (recipes cd there
# first); ROOT_PY is the same interpreter seen from the repository root.
# Windows virtualenvs put the binary in Scripts/, POSIX ones in bin/.
ifneq ($(wildcard backend/.venv/Scripts/python.exe),)
PY := .venv/Scripts/python.exe
ROOT_PY := backend/.venv/Scripts/python.exe
else ifneq ($(wildcard backend/.venv/bin/python),)
PY := .venv/bin/python
ROOT_PY := backend/.venv/bin/python
else
# No virtualenv yet: fall back to whatever python is on PATH. Run `make setup`.
PY := python
ROOT_PY := python
endif

COMPOSE := docker compose

.DEFAULT_GOAL := help

.PHONY: help setup up down logs migrate revision seed reset-db \
        api worker beat web assistant \
        test test-backend test-frontend test-assistant \
        lint format typecheck coverage secrets check

## ---------------------------------------------------------------------------
## help
## ---------------------------------------------------------------------------
help:
	@echo "AI Job Application Agent"
	@echo ""
	@echo "  Setup"
	@echo "    setup           Create .env, build the backend venv, install all node deps"
	@echo "    secrets         Print freshly generated SECRET_KEY / ENCRYPTION_KEY / BROWSER_ASSISTANT_TOKEN"
	@echo ""
	@echo "  Docker stack"
	@echo "    up              Build and start postgres, redis, api, worker, beat, web"
	@echo "    down            Stop the stack (named volumes are kept)"
	@echo "    logs            Follow logs from every service"
	@echo ""
	@echo "  Database"
	@echo "    migrate         alembic upgrade head"
	@echo "    revision        New autogenerated migration:  make revision m=\"add widgets\""
	@echo "    seed            Seed the owner account, placeholder profile and sample jobs"
	@echo "    reset-db        Drop, recreate and reseed. DESTROYS local data."
	@echo ""
	@echo "  Run locally (no docker)"
	@echo "    api             uvicorn with reload on 127.0.0.1:8000"
	@echo "    worker          celery worker"
	@echo "    beat            celery beat scheduler"
	@echo "    web             next dev on 3000"
	@echo "    assistant       browser assistant, HEADED, on this machine only"
	@echo ""
	@echo "  Quality"
	@echo "    test            Backend, frontend and assistant suites"
	@echo "    test-backend    pytest"
	@echo "    test-frontend   vitest"
	@echo "    test-assistant  assistant suite"
	@echo "    lint            ruff check + next lint"
	@echo "    format          ruff format and autofix"
	@echo "    typecheck       mypy + tsc --noEmit"
	@echo "    coverage        pytest with an HTML coverage report"
	@echo "    check           lint, typecheck and test. Run this before committing."
	@echo ""
	@echo "  Interpreter in use: $(ROOT_PY)"

## ---------------------------------------------------------------------------
## setup
## ---------------------------------------------------------------------------
setup:
	@test -f .env || (cp .env.example .env && echo "Created .env from .env.example - now run 'make secrets' and paste the values in")
	@test -f frontend/.env.local || cp frontend/.env.example frontend/.env.local
	@test -d backend/.venv || python -m venv backend/.venv
	@mkdir -p backend/storage
	cd backend && $(PY) -m pip install --upgrade pip
	cd backend && $(PY) -m pip install -r requirements-dev.txt
	cd frontend && npm install
	cd browser-assistant && npm install
	@echo "Setup done. Next: make secrets, then edit .env, then make migrate seed"

## ---------------------------------------------------------------------------
## docker stack
## ---------------------------------------------------------------------------
up:
	$(COMPOSE) up -d --build

down:
	$(COMPOSE) down

logs:
	$(COMPOSE) logs -f --tail=200

## ---------------------------------------------------------------------------
## database
## ---------------------------------------------------------------------------
migrate:
	cd backend && $(PY) -m alembic upgrade head

revision:
	@test -n "$(m)" || (echo 'Usage: make revision m="short description"' && exit 1)
	cd backend && $(PY) -m alembic revision --autogenerate -m "$(m)"

seed:
	cd backend && $(PY) -m seed.seed

reset-db:
	@echo "This drops every table in DATABASE_URL and reseeds."
	cd backend && $(PY) -m seed.seed --reset

## ---------------------------------------------------------------------------
## run locally
## ---------------------------------------------------------------------------
api:
	cd backend && $(PY) -m uvicorn app.main:app --reload --host 127.0.0.1 --port 8000

worker:
	cd backend && $(PY) -m celery -A app.workers.celery_app worker --loglevel=INFO --concurrency=2

beat:
	cd backend && $(PY) -m celery -A app.workers.celery_app beat --loglevel=INFO

web:
	cd frontend && npm run dev

# The browser assistant is intentionally not a docker service. It runs headed,
# on your own machine, under your own browser profile, with you watching it. It
# never bypasses CAPTCHAs, bot detection, logins or platform rules: when it hits
# one, it stops and files a review task with the link and the prefilled draft.
assistant:
	cd browser-assistant && npm run start

## ---------------------------------------------------------------------------
## quality
## ---------------------------------------------------------------------------
test: test-backend test-frontend test-assistant

test-backend:
	cd backend && $(PY) -m pytest

test-frontend:
	cd frontend && npm test

test-assistant:
	cd browser-assistant && npm test

lint:
	cd backend && $(PY) -m ruff check .
	cd frontend && npm run lint

format:
	cd backend && $(PY) -m ruff format .
	cd backend && $(PY) -m ruff check --fix .

typecheck:
	cd backend && $(PY) -m mypy app
	cd frontend && npm run typecheck
	cd browser-assistant && npm run typecheck

coverage:
	cd backend && $(PY) -m pytest --cov=app --cov-report=term-missing --cov-report=html

## ---------------------------------------------------------------------------
## secrets
## ---------------------------------------------------------------------------
# Prints values for .env. Generated locally, never committed, never logged.
# Rotating ENCRYPTION_KEY? Move the old value to ENCRYPTION_KEY_PREVIOUS first.
secrets:
	@echo "# Paste these into .env. Keep them out of version control."
	@$(ROOT_PY) -c "import secrets; print('SECRET_KEY=' + secrets.token_urlsafe(64))"
	@$(ROOT_PY) -c "from cryptography.fernet import Fernet; print('ENCRYPTION_KEY=' + Fernet.generate_key().decode())"
	@$(ROOT_PY) -c "import secrets; print('BROWSER_ASSISTANT_TOKEN=' + secrets.token_urlsafe(48))"

## ---------------------------------------------------------------------------
## check
## ---------------------------------------------------------------------------
check: lint typecheck test
	@echo "All checks passed."
